name: Sync to GitLab

on:
  push:
    branches:
      - main  # or the branch you want to sync

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # This ensures a full clone is performed

    - name: Set up Git configuration
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Fetch changes from GitLab
      run: |
        git remote add gitlab https://oauth2:${GITLAB_TOKEN}@gitlab.com/mqwele/consul-hashicorp.git
        git fetch gitlab

    - name: Pull changes from GitLab
      run: |
        git pull gitlab main

    - name: Push changes to GitLab
      env:
        GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
      run: |
        git push gitlab main:main
